Add 2-D plot (only encoder now)
necst-telescope/observer pull request #89
Opened 2024-08-03 06:17 UTC by Kirby1717

**Checks**

- [ ] Debugging completed
- [ ] Please debug me

**Related Issue**

This PR closes #13.

2024-08-03 06:19 UTC, Kirby1717 commented
@TatsumiISHIKAWA 
開発の現状として
- AzEl plot はできる
- SIS I-V は実装を試みているがうまく表示されない (昨日のテストにて)
- 任意の 2 軸を表示することはまだできない (選べない)

という状況ですので、把握よろしくお願いします。

2024-08-03 14:13 UTC, TatsumiISHIKAWA requested changes
- こちらで必要な変更をしておきます。

2024-08-03 14:13 UTC, TatsumiISHIKAWA commented on observer/static/chart.js
> +        } else if (this.drawingArray) {
ここの変数を変更することで値に制限が付きそうです。
本来はAz-Elプロットのみで制限がかかるようにすべきですが、とりあえずNANTEN2の駆動試験で使いたいので固定しておきます。
今後トピックによって変更できるようにすべきです。

2024-08-03 14:26 UTC, TatsumiISHIKAWA approved these changes
LGTM! とりあえずMergeします。

2024-08-03 14:26 UTC, merged

2024-08-04 07:36 UTC, Kirby1717 commented on observer/static/chart.js
> +        } else if (this.drawingArray) {
把握しました。
レビューありがとうございます。